name: fotofocus
description: FotoFocus - Learn photography with challenges and community.
publish_to: "none"

version: 1.0.0+1


  
environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter  
  image_picker: ^1.1.2 


  cupertino_icons: ^1.0.8

  # HTTP + storage + state
  http: ^1.2.2
  flutter_secure_storage: ^9.2.2
  provider: ^6.1.2

  photo_view: ^0.15.0
  dio: ^5.7.0
  saver_gallery:
    path: packages/saver_gallery_fixed
  permission_handler: ^11.3.1
  device_info_plus: ^10.1.2
  shared_preferences: ^2.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/logo.png

  # If you have Inter font locally, add it here.
  # fonts:
  #   - family: Inter
  #     fonts:
  #       - asset: assets/fonts/Inter-Regular.ttf
  #       - asset: assets/fonts/Inter-SemiBold.ttf
  #         weight: 600
  #       - asset: assets/fonts/Inter-Bold.ttf
  #         weight: 700

  # assets:
  #   - assets/images/
